### ISSUE TITLE
Add a note to point to the source of the binaries

### ISSUE THREAD

**Issue by ctron** [eclipse-equinox/equinox.binaries#3]
There must be source code and a build process how these binaries got created. It would be helpful if this repository (e.g. in a README.md) explains where the code is and how the build works.

**Comment by laeubi** [comment]
@akurtakov @tjwatson can you help here? I would also be interested how this works.

**Comment by akurtakov** [comment]
Build is https://ci.eclipse.org/releng/job/Build-eclipse-launcher/ which uses sources from https://github.com/eclipse-equinox/equinox/tree/master/features/org.eclipse.equinox.executable.feature/library .  For more detailed reply I would have to defer to @sravanlakkimsetti .

**Comment by sravanlakkimsetti** [comment]
The exe build is triggered by

1. Linux [build.sh](https://github.com/eclipse-equinox/equinox/blob/master/features/org.eclipse.equinox.executable.feature/library/gtk/build.sh)
2. Mac  [build.sh](https://github.com/eclipse-equinox/equinox/blob/master/features/org.eclipse.equinox.executable.feature/library/cocoa/build.sh)
3. Windows [build.bat](https://github.com/eclipse-equinox/equinox/blob/master/features/org.eclipse.equinox.executable.feature/library/win32/build.bat)

You may pass the optional arguments for these commands
```
       -output <PROGRAM_OUTPUT>  - executable filename ("eclipse")
       -os     <DEFAULT_OS>      - default Eclipse "-os" value
       -arch   <DEFAULT_OS_ARCH> - default Eclipse "-arch" value
       -ws     <DEFAULT_WS>      - default Eclipse "-ws" value
       -java <JAVA_HOME>  - java install for jni headers
```

**Comment by laeubi** [comment]
@sravanlakkimsetti many thanks I'll try to take a look into this, one question, can you tell a bit what the "launcher binary" does? Is it meant to interact with the `eclipse.exe` (so there is some code to call into that part) or is it just calling to some (system dependent) native APIs (which ones?)

**Comment by HannesWell** [comment]
Isn't the 'launcher binary' the eclipse.exe?AFAICT that's a little C Programme that is processing the ini-file and launches a Java-process with resulting/required Argumentes and the specified JVM.

**Comment by iloveeclipse** [comment]
... plus sets some environment variables, checks if Eclipse wanted to be restarted, shows spash and error dialogs etc.

**Comment by laeubi** [comment]
No the _launcher_ binary is (for example) here what is a shared library:
https://github.com/eclipse-equinox/equinox.binaries/tree/master/org.eclipse.equinox.launcher.gtk.linux.x86_64

The _executable_ is here:
https://github.com/eclipse-equinox/equinox.binaries/tree/master/org.eclipse.equinox.executable/bin/gtk/linux/x86_64

**Comment by iloveeclipse** [comment]
I believe what you are looking for is https://github.com/eclipse-equinox/equinox/tree/master/features/org.eclipse.equinox.executable.feature/library

**Comment by HannesWell** [comment]
With https://github.com/eclipse-equinox/equinox/pull/640 a note is added to the CONTRIBUTING section of the equinox repository.
Do you think that's sufficient or should I also add a reference to that section from this repository?

**Comment by HannesWell** [comment]
Added a note with #5. Please let me know if something is not clear.
